### ISSUE TITLE
Problem with React raised button

### ISSUE THREAD

**Issue by clairenied15** [jcsambangi/bme590final#16]
I am currently working through Suyash's React tutorial and just copying what he does to learn the basics of React. Since this is only practice, I am working on my own machine and not pushing anything to GitHub. I am encountering an error when trying to add the Raised Button. I am almost positive that I have the same code as in the tutorial. Here is the error in my web browser:

![image](https://user-images.githubusercontent.com/42756895/49347508-15a80080-f66d-11e8-983f-988c3614e423.png)

**Comment by clairenied15** [comment]
And here is my code (sorry that I have to use screenshots since it is not on GitHub):

![image](https://user-images.githubusercontent.com/42756895/49347521-438d4500-f66d-11e8-88fc-9acf6a9e58d6.png)

![image](https://user-images.githubusercontent.com/42756895/49347525-4f790700-f66d-11e8-89e2-4ceb5a8bb0a8.png)

**Comment by jcsambangi** [comment]
@clairenied15 Did you run `npm install material-ui --save` in the command line, while inside your project?

**Comment by clairenied15** [comment]
Yep

**Comment by clairenied15** [comment]
In my node_modules folder, there is a material-ui folder with folders for Avatar, Buttons, etc. so I'm assuming that material-ui "downloaded" correctly

**Comment by jcsambangi** [comment]
Odd... Hopefully Suyash will be able to weigh in. Only thing I will say is that I actually used `npm install @material-ui/core --save` and then in my code did `import Button from '@material-ui/core/Button';
`. I did see that Suyash used your syntax, but I also think he gave that lecture a while ago and maybe that syntax is deprecated now. It may be worth trying the newer syntax and seeing whether it makes a difference (to make it a raised button with the new syntax, I think you can do something like this: `<Button variant='raised' />`). Let me know how it goes - if you have time tomorrow we can also meet up to look at it, just lmk.

**Comment by clairenied15** [comment]
@suyashkumar Do you have any idea what could be causing this error? It doesn't make sense to me why there is a problem with the "Paper" module when I'm not even using/calling it.

**Comment by clairenied15** [comment]
And now in App.js and Sites.js I see an error that says "Error:Node interpreter path is incorrect. Please check interpreter settings"
