### ISSUE TITLE
Post-Download Log Report: "folders created"

### ISSUE THREAD

**Issue by clairenied15** [jcsambangi/bme590final#20]
@mlp6 What does it mean in the assignment when it says to include "folders created" in the log report? We aren't really creating folders, just storing the data.

**Comment by mlp6** [comment]
Yes, that was a bit confusing... I really just mean capture the path associated with the files, or the directory structure that Dr. Luck has requested be preserved.

**Comment by jcsambangi** [comment]
@mlp6 Are we saving the data? Or the files? Until now, we've been storing the data from each file as a string in a MySQL database (with associated time and pin). But it sounds like maybe we are supposed to be replicating the file structure from each DASHR somewhere on the user's local machine? And just using the database to log the history of what transfers we've done?

**Comment by mlp6** [comment]
You want to be saving the data... I think that Jason wanted the directory structure b/c that conveyed information about the files, but if you are otherwise collecting that information in the database, then you can always recreate that.

**Comment by jcsambangi** [comment]
Should not be an issue considering times are harvested from the files and stored as the primary identifier for the data.
