### ISSUE TITLE
How to center Tables in React

### ISSUE THREAD

**Issue by clairenied15** [jcsambangi/bme590final#21]
@suyashkumar I am having trouble trying to center the table in the post-download log report (using React). I tried using `alignItems: 'center'` in the table and root styles, but it didn't work. 

https://github.com/jcsambangi/bme590final/blob/61f21c4e28951218aff1297ed0161f29c36ac258/src/LogTable.js#L11-L22

**Comment by suyashkumar** [comment]
@clairenied15 can you try giving the table the `margin: auto` style? If that doesn't work can you try that on it's enclosing div? If neither works, lmk and I'll pull the code and work through it with you
