### ISSUE TITLE
"Link to deployed web service"

### ISSUE THREAD

**Issue by jcsambangi** [jcsambangi/bme590final#32]
@mlp6 One of the deliverables listed for the HIE project is a link to a deployed web service. Our setup is a ReactJS front end running on localhost:3000 that makes RESTful API calls to a Python back end running on localhost:5000, which in turn communicates with a local MySQL database to store the data read from user selected files. So does the web service deliverable apply in our case?

**Comment by mlp6** [comment]
You are good... "web service" really should just be "implement a RESTful API", which in your case, can run locally.
