### ISSUE TITLE
Video demo of our tool in action

### ISSUE THREAD

**Issue by clairenied15** [jcsambangi/bme590final#34]
@mlp6 We recorded a video of our HIE tool on an iPhone. How do you want us to turn this in? Is there a way to put this on GitHub?

**Comment by mlp6** [comment]
How large is the video file?

**Comment by mlp6** [comment]
If the video is large (GitHub has a max size of 100 MB in the free version), you can upload to something like Google Drive, Box, Dropbox, and share the URL in the `README.md` file.

**Comment by clairenied15** [comment]
I can't find the size of the file because every time I try to email it to myself from my phone, I get an error. It's a 3 minute long video, so the file is probably quite large. That being said, I still need to find a way to get it ti Drop Box from my phone since it won't allow it to be emailed. Hopefully, I can just log into DropBox from my phone and upload it.
