### ISSUE TITLE
Set up GUI

### ISSUE THREAD

**Issue by clairenied15** [jcsambangi/bme590final#7]
Possibly jupyter notebook

**Comment by jcsambangi** [comment]
If we use React, are we still responsible for unit tests, Travis CI, and Sphinx for the front end? @mlp6 @suyashkumar @dward2

**Comment by mlp6** [comment]
Ideally, yes, but you may need to use different infrastructure for ReactJS:
* https://reactjs.org/community/testing.html
* https://react-styleguidist.js.org/docs/documenting.html
* https://github.com/reactjs/react-docgen

Travis should be able to accommodate ReactJS directly, or you can use some explicit setup commands to run your tests.
